### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by dwightee** [KuechA/pestudio-cli#1]
Hi, I was trying your PE-analyzer. It seems like the header option is not working, not even on your example.
Am I doing something wrong, here ?

terminal: 
`Entering interactive mode...
Please specify file to analyze or type help
>> f ./tests/tls_upx.exe
>> header
Printing header
Traceback (most recent call last):
  File "pestudio.py", line 507, in <module>
    interactiveMode(args.file)
  File "pestudio.py", line 286, in interactiveMode
    peAnalyzer.printHeaderInformation()
  File "/Users/mates/Documents/MALWARE/PE-Studio/pestudio-cli-master/PeAnalyzer.py", line 1146, in printHeaderInformation
    table.add_row(["Machine", constants.MACHINE_TYPE[machine]])
KeyError: MACHINE_TYPES.I386`

**Comment by KuechA** [comment]
Hi, unfortunately I don't have the time to debug the error in detail. However, it seems like LIEF, one of our dependencies, changed its API and now returns an enum instead of an integer as machine type. You could try to fix it by using `machine.value` as key in line 1146 instead of only `machine` or to use an older version of LIEF.
